### ISSUE TITLE
fix drag and drop logic

### ISSUE THREAD

**Issue by nat-nat33** [zakattack9/Lanakila-Meals-on-Wheels-Project#21]
when more than one message is dropped in message area the first message gets pushed to the group area, should go back to the message area. Only messages should go to message area, only groups should go to group area.

<img width="1093" alt="screen shot 2018-03-08 at 2 08 18 pm" src="https://user-images.githubusercontent.com/16570585/37183467-50d9dde8-22da-11e8-85fd-078559e64ed4.png">

**Comment by zakattack9** [comment]
fixed bug with simple conditional
